### ISSUE TITLE
Error on Run after install dependences and setup ewelink developer account

### ISSUE THREAD

**Issue by fnandomaia** [nocmt/eWeLinkOAuthLoginDemo#12]
Hello. 
What am I doing wrong to run the code using **_node controlDeviceDemo.js_** ? 
Please, check erros as following:
![20240220-014735-001](https://github.com/nocmt/eWeLinkOAuthLoginDemo/assets/5240596/9ac480b9-1a0a-4ac8-a979-11d3c3470050)

All dependences were installed.

File config.js is ok.
![20240220-015043-002](https://github.com/nocmt/eWeLinkOAuthLoginDemo/assets/5240596/de5fdcf4-4590-4a14-869f-be66995c0bf4)

My account is created and configured fine:
![20240220-015237-003](https://github.com/nocmt/eWeLinkOAuthLoginDemo/assets/5240596/5e4904b1-4ca7-4e20-9007-eb2c564656c5)

**Comment by nocmt** [comment]
Check the package.json file：

<img width="593" alt="image" src="https://github.com/nocmt/eWeLinkOAuthLoginDemo/assets/26828323/36613419-5b58-4f2b-aad2-8893a0d80947">
