### ISSUE TITLE
Update to documenation

### ISSUE THREAD

**Issue by carylewis** [nocmt/eWeLinkOAuthLoginDemo#17]
I think it would be useful to highlight that this project requires that the redirect url be set in the app to:

http://127.0.0.1:8000/redirectUrl

Otherwise you get a rediret url not authorized.

Also rediret is spelled incorrectly.

**Comment by nocmt** [comment]
<img width="1679" alt="image" src="https://github.com/nocmt/eWeLinkOAuthLoginDemo/assets/26828323/7e4e8194-3b9e-4085-b440-ecaa52df163a">

The document has stated the requirement to fill in: http://127.0.0.1:8000/redirectUrl Also, I did not find the word redirect. Please confirm the situation again.
