### ISSUE TITLE
Doesn't show any devices

### ISSUE THREAD

**Issue by elwin-jacellc** [nocmt/eWeLinkOAuthLoginDemo#3]
Was able to use the script to update the token, but running controlDeviceDemo.js returns zero devices. I just want to be able to issue API command to turn on and off a single device. The update has made this process extremely difficult and frustrating.

**Comment by coolkit-carl** [comment]
> Was able to use the script to update the token, but running controlDeviceDemo.js returns zero devices. I just want to be able to issue API command to turn on and off a single device. The update has made this process extremely difficult and frustrating.

This is because the authorized APPID can only obtain devices from sonoff, coolkit, and SONOFF brands. If the devices under your account belong to other brands, in theory, authorization is required to use them to avoid legal issues.

**Comment by elwin-jacellc** [comment]
I can see the device in the ewelink web portal and ewelink app. Any ideas on how to authorize the device?

**Comment by coolkit-carl** [comment]
> 我可以在 ewelink 门户网站和 ewelink 应用程序中看到该设备。关于如何授权设备有什么想法吗？

因为涉及到品牌授权，对于付费的企业客户，我们是协助他们去联系厂家得到授权，你可以告诉我你使用的设备ID，我查一下品牌是不是可以免费授权。

**Comment by pazzagsi2** [comment]
Hi,

the deviceid=1000830256 brand "new smart" is enableable?

alternatively, can you give me an example of how it is possible to request the status of a single device?

thank you

**Comment by coolkit-carl** [comment]
> Hi,
> 
> the deviceid=1000830256 brand "new smart" is enableable?
> 
> alternatively, can you give me an example of how it is possible to request the status of a single device?
> 
> thank you

This device does not support returning data

```
client.at = LoggedInfo.data?.accessToken
client.region = LoggedInfo?.region || 'eu'
client.setUrl(LoggedInfo?.region || 'eu')
const deviceStatus = await client.device.getThingStatus({ type: 1, id: "1000830256"})
```

**Comment by pazzagsi2** [comment]
Hi,
the command works, but of course it only responds with a part of the data


<<
{
  status: 200,
  responseTime: 452,
  error: 0,
  msg: '',
  data: {
    params: {
      bindInfos: [Object],
      version: 8,
      sledOnline: 'off',
      ssid: 'XXXX',
      bssid: '00:00:00:00:00:00',
      switch: 'off',
      fwVersion: '3.5.1',
      rssi: -55,
      staMac: 'C4:4F:33:xx:xx:xx',
      startup: 'off',
      init: 1,
      pulse: 'off',
      pulseWidth: 500,
      zyx_watch_control: true
    }
  }
}

>>

with the old function because it returns all the values of the device? Can you confirm that there is no way to recover the missing values, for example the name?

```
const ewelink = require('ewelink-api');
//
//
        var i = 0;
        var j = 0;
        async function asyncCall(device) {

        /* instantiate class */
        const connection = new ewelink({
        email: 'xxxxxxxx@gmail.com',
                password: 'xxxxxxxx',
                region: 'eu',
        });
                /* get all devices */
                  const status = await connection.getDevice('1000830256');

                console.log(status);
             
                console.log("______________");
        }


asyncCall();
```


<<
 _id: 'xxxxx',
  family: { room: {}, members: [], id: 'xxxxx', index: 0 },
  group: '',
  online: true,
  groups: [],
  devGroups: [],
  relational: [],
  deviceid: '1000830256',
  name: 'nome device',
  type: '10',
  apikey: '4dcd9a8c-7062-ccc-b5af-6683d701b6b7',
  extra: {
    _id: '5c8612dcdcdc5bbb859a',
    apikey: '08cc10c0-ede2-43db-85be-0a66dcdcd5321',
    extra: {
      uiid: 6,
      description: '20190311003',
      brandId: '5735f5f906d9751d4f109629',
      apmac: 'xx:27:01:xx:xx:xx',
 
     
      modelInfo: '589833ac2f979b623e2f503f',
      model: 'PSF-B01-GL',
      manufacturer: '郑州市中原区汇诚电子材料经营部',
  
      chipid: '00897DA4'
    },
    country: 'CN',
    expiredAt: '2024-03-09T07:45:16.823Z',
    deviceid: '1000830256',
    createdAt: '2019-03-11T07:45:16.823Z'
  },
  settings: {
    opsNotify: 0,
    opsHistory: 1,
    alarmNotify: 1,
    wxAlarmNotify: 0,
    wxOpsNotify: 0,
    wxDoorbellNotify: 0,
    appDoorbellNotify: 1
  },
  params: {
    bindInfos: { ifttt: [Array] },
    version: 8,
    sledOnline: 'off',
    ssid: 'xxxx',
    bssid: '00:00:00:00:00:00',
    switch: 'off',
    fwVersion: '3.5.1',
    rssi: -55,
    staMac: 'C4:4F:33:xx:xx:xx',
    startup:

>>

**Comment by coolkit-carl** [comment]
> client.at = LoggedInfo.data?.accessToken
> client.region = LoggedInfo?.region || 'eu'
> client.setUrl(LoggedInfo?.region || 'eu')
> const deviceStatus = await client.device.getThingStatus({ type: 1, id: "1000830256"})

One is to obtain the current status of the device, and the other is to obtain complete information of the device. Please distinguish between them. The documents are both written. 

If you want to obtain complete device information:

```
client.at = LoggedInfo.data?.accessToken
client.region = LoggedInfo?.region || 'eu'
client.setUrl(LoggedInfo?.region || 'eu')
const deviceStatus = await client.device.getThings({ thingList: [{itemType: 1, id: "1000830256"}]})
```

**Comment by pazzagsi2** [comment]
HI,

Thanks for your advice, I fixed it.

I needed all the device information to update my product with the new API.

Now I get them perfectly
```

   client.at = LoggedInfo.data?.accessToken
             client.region = LoggedInfo?.region || 'eu'
             client.setUrl(LoggedInfo?.region || 'eu')
             const deviceStatus = await client.device.getThings({thingList: [{itemType: 3, id: "1000830256"}]})
            
             console.log("--4-", deviceStatus.data.thingList[0]);
```

To complete the migration, I just need to be able to get the token refresh to work, it doesn't work for me either and it expires after a few hours. If I fail I will ask you in the other post

Thanks for your quick advice
