### ISSUE TITLE
  msg: 'cannot found access token info',

### ISSUE THREAD

**Issue by apadilla83** [nocmt/eWeLinkOAuthLoginDemo#4]
Hi, after a short time, i received this ms when a try to control a device. I don't understand because  token are not expired. If I login manually again to refresh token, the api work again. There any way to refresh token automatically without login manually again??
thanks

**Comment by nocmt** [comment]
You can write a scheduled task to refresh the token at regular intervals, or check if the token has expired while you are using it. If it has expired, simply refresh or log in again.

**Comment by apadilla83** [comment]
> You can write a scheduled task to refresh the token at regular intervals, or check if the token has expired while you are using it. If it has expired, simply refresh or log in again.

HI!, when I refresh the token manually , when I get msg: 'cannot found access token info' or by regular intervals. First times work, but after a while I received this:

{
  status: 200,
  responseTime: 507,
  error: 405,
  msg: "can't find the account with this rt!",
  data: {}
}

I used the function of demo to refresh token:

const refreshStatus = await client.user.refreshToken({
￼      rt: LoggedInfo.data?.refreshToken,
￼    })

thanks!

**Comment by Z0lid** [comment]
Having the same issue, can't refresh token.
