### ISSUE TITLE
Update or fix needed for vulnerable dependancy

### ISSUE THREAD

**Issue by brianmcentire** [nocmt/eWeLinkOAuthLoginDemo#6]
$ npm i

up to date, audited 103 packages in 343ms

14 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

$ npm audit
# npm audit report

axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
No fix available
node_modules/axios
  ewelink-api-next  *
  Depends on vulnerable versions of axios
  node_modules/ewelink-api-next

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

**Comment by nocmt** [comment]
Okay, I will check and try to fix it.
