### ISSUE TITLE
controlDeviceDemo.js doesn't report correct device power

### ISSUE THREAD

**Issue by brianmcentire** [nocmt/eWeLinkOAuthLoginDemo#7]
First off, thanks for creating this project and the helpful documentation for getting it running!

I think there is either a bug in the API or this project, not sure which.

When I run controlDeviceDemo.js, a list of my Sonoff S31 smart plugs is returned with lots of correct information -- the name, the switch (on/off) state, etc. But the power value is "stuck". It will show 31 watts, for example even when the switch is off. If I place a different load on the switch, and turn it on, still the same value of 31 watts will be returned by the demo.

Here's where it gets interesting: If I open the eWeLink app and observe the power level of the smart plug device in my app, then rerun the controlDeviceDemo.js ... the power value is correct! So it's like I have to use the app to make something update something so that controlDeviceDemo.js can return the proper value for power.

**Comment by coolkit-carl** [comment]
This is not a bug, it is just a status update strategy. It is recommended to review the Long Connection Protocol documentation:

https://coolkit-technologies.github.io/eWeLink-API/#/en/UIIDProtocol?id=uiid5-power-detection-single-channel-plug

<img width="1558" alt="image" src="https://github.com/coolkit-carl/eWeLinkOAuthLoginDemo/assets/50738270/7acb8a52-15d7-4d82-af46-9c06de87a7ed">
