### ISSUE TITLE
The path of request is not allowed with appid

### ISSUE THREAD

**Issue by DevJaGz** [nocmt/eWeLinkOAuthLoginDemo#8]
After make a request to https://apia.coolkit.cn/v2/utils/get-region?countryCode=34, I got the next response:

{
    "error": 407,
    "msg": "the path of request is not allowed with appid:ZJpJmcx8xeoytJ7nbWtY4tXailh3mLTX",
    "data": {}
}

I do not know what is wrong with my app id, could anyone help me please?

**Comment by nocmt** [comment]
At present, the application types created through the developer platform are limited to accessing OAuth2.0 related interfaces. There is a list of interfaces in the application details.

<img width="684" alt="image" src="https://github.com/nocmt/eWeLinkOAuthLoginDemo/assets/26828323/be11a017-8b7f-4a1b-9863-8b396cddeab6">
